module.exports = [
  require('./docType'),
  require('./componentType'),
  require('./module'),
  require('./section'),
  require('./name'),
  require('./parentId'),
  require('./id'),
  require('./path'),
  require('./param'),
  require('./property'),
  require('./requires'),
  require('./restrict'),
  require('./returns'),
  require('./eventType'),
];